// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugjsuzomcsktvnsvorcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnanN1em9tY3NrdHZuc3ZvcmN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2NzcyMjQsImV4cCI6MjA0OTI1MzIyNH0.nnz5pMbT2Zp5Z2iLBFLHxmS7nvCbGrMr7w5V9p-o3TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);